import { images } from "./images";

export const projectCategories = [
  { id: "all", label: "All Projects" },
  { id: "frontend", label: "Frontend" },
  { id: "backend", label: "Backend" },
  { id: "fullstack", label: "" },
];

export const projects = [
  {
    id: "1",
    title: "Sunnah Store",
    description: "Online Store for halal businesses",
    category: "web",
    stack: "MERN Stack",
    image: images.projects.halalJibika,
    technologies: ["Next.js", "Tailwind", "AuthJs"],
    liveUrl: "https://e-coomerce-project.vercel.app/",
    githubUrl: "https://github.com/MdAthikhasan/e-coomerce-project",
  },
  {
    id: "2",
    title: "Healthcare Website",
    description: "A modern healthcare platform for online consultations.",
    category: "web",
    stack: "WordPress",
    image: images.projects.healthmedical,
    technologies: ["Elementor", "WordPress"],
    liveUrl: "https://remediservice.net/",
  },
  {
    id: "3",
    title: "Restaurant Website",
    description: "A restaurant website to showcase menu and take reservations.",
    category: "web",
    stack: "WordPress",
    image: images.projects.resturant,
    technologies: ["Elementor", "WordPress"],
    liveUrl: "https://moraindiancuisine.se/",
  },
  {
    id: "4",
    title: "Institutional Website",
    description: "Information and services for students",
    category: "web",
    stack: "MERN Stack",
    image: images.projects.eLearning,
    technologies: ["React", "Bootstrap"],
    liveUrl: "https://bou-university-design.vercel.app/",
    githubUrl: "https://github.com/MdAthikhasan/bou-university-design",
  },
  {
    id: "5",
    title: "Funeral Website",
    description: "A modern funeral website for managing funeral services.",
    category: "web",
    stack: "WordPress",
    image: images.projects.btf,
    technologies: ["Elementor", "WordPress"],
    liveUrl: "https://blacktulipfunerals.com.au/home",
  },
  {
    id: "6",
    title: "Task Management Todo app",
    description: "Application for managing tasks and projects",
    category: "frontend",
    stack: "MERN Stack",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcToOdMXwSSkScnMIPwA6y1MOeNcL9-3tTbj9ac6mlTTae-6xdClLJiMsdtWCNe7dNlhvZg&usqp=CAU",
    technologies: ["React", "Tailwind CSS"],
    liveUrl: "https://task-management-jet.vercel.app/",
    githubUrl: "https://github.com/MdAthikhasan/Task-management",
  },
  {
    id: "7",
    title: "Personal Website",
    description: "Personal portfolio website",
    category: "frontend",
    stack: "MERN Stack",
    image:
      "https://market-resized.envatousercontent.com/previews/files/602725017/preview_01.jpg?w=590&h=300&cf_fit=crop&crop=top&format=auto&q=85&s=f39831e1ef4e912898524370d5c44efb1d2bffb4a830e0890331523745f64680",
    technologies: ["React", "Tailwind CSS"],
    liveUrl: "https://mamu-seven.vercel.app/",
    githubUrl: "https://github.com/MdAthikhasan/mamu",
  },
  {
    id: "8",
    title: "Dua page",
    description: "A dua page where practical muslim can read dua.",
    category: "frontend",
    stack: "MERN Stack",
    image: "https://i.postimg.cc/9Q02RQ8M/duapage.png",
    technologies: ["Next.js", "Tailwind CSS"],
    liveUrl: "https://assignment-44f2.vercel.app/",
    githubUrl: "https://github.com/MdAthikhasan/assignment",
  },
  {
    id: "9",
    title: "Roadmap app",
    description: "Modern roadmap-app for knowing user feedback.",
    category: "frontend",
    stack: "MERN Stack",
    image: "https://i.postimg.cc/VLRs0Tz7/roadmap.png",
    technologies: ["React", "Tailwind CSS"],
    liveUrl: "https://roadmapapp-front-end.vercel.app/",
    githubUrl: "https://github.com/MdAthikhasan/roadmapapp-front-end",
  },
  {
    id: "10",
    title: "Bank Website",
    description: "Bank platform focused on Practicing purpuse.",
    category: "web",
    stack: "MERN Stack",
    image: "https://i.ibb.co/JzFRZ9p/bank-website.jpg",
    technologies: ["React.js", "Tailwind CSS"],
    liveUrl: "https://bank-app-pearl.vercel.app/",
    githubUrl: "https://github.com/MdAthikhasan/Bank-app-",
  },
  {
    id: "11",
    title: "E-commerce Website",
    description: "A modern e-commerce platform for online shopping.",
    category: "web",
    stack: "WordPress",
    image: "https://i.postimg.cc/KY7XwPV9/woodmart-shop.png",
    technologies: ["Woodmart Theme", "Elementor", "WordPress"],
    liveUrl: "https://dev-woodmart-newsite.pantheonsite.io/",
  },
  {
    id: "12",
    title: "Blog website",
    description: "A blog website for sharing articles and insights.",
    category: "web",
    stack: "WordPress",
    image: images.projects.blogsite,
    technologies: ["Custom Theme", "PHP", "WordPress"],
    liveUrl: "https://dev-my-custom-theme.pantheonsite.io/",
  },
  {
    id: "13",
    title: "Smart Invoice generator",
    description: "Generate professional invoices easily",
    category: "web",
    stack: "MERN Stack",
    image: "https://i.postimg.cc/yNHvr4M7/invoice.png",
    technologies: ["React.js", "Tailwind CSS"],
    liveUrl: "https://smart-invoice-generator-tau.vercel.app/",
    githubUrl: "https://github.com/MdAthikhasan/smart-invoice-generator",
  },
  {
    id: "14",
    title: "Learning Management website",
    description: "A learning management system for online courses.",
    category: "web",
    stack: "WordPress",
    image: "https://i.postimg.cc/mg9q01ps/education-photo.png",
    technologies: ["WordPress", "Elementor", "Tutor LMS"],
    liveUrl: "https://dev-learning-management-web.pantheonsite.io/",
  },
  {
    id: "15",
    title: "Real Estate Website",
    description:
      "A modern real estate platform for buying and renting properties.",
    category: "web",
    stack: "MERN Stack",
    image: images.projects.realestate,
    technologies: ["React", "Tailwind CSS"],
    liveUrl: "https://real-estate-xi-opal.vercel.app/",
  },
];
